//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SickeCell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public string ClientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Middle_Initial { get; set; }
        public string UniqueID { get; set; }
        public string DOB { get; set; }
        public string Age { get; set; }
        public string AgeGroup { get; set; }
        public string Ageat { get; set; }
        public string Gender { get; set; }
        public string Race { get; set; }
        public string Ethnicity { get; set; }
        public string SSN { get; set; }
        public string Mobile_Number { get; set; }
        public string FullStreetAddress { get; set; }
        public string FullStreetAddress2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string CountyCode { get; set; }
        public string CountyCodeDescription { get; set; }
        public string PhoneNumber { get; set; }
        public string Eligibility { get; set; }
        public string SickleCellDiagnosis { get; set; }
        public string PMPProviderName { get; set; }
        public string Specialist { get; set; }
        public string CCUCase { get; set; }
        public string Email_Address { get; set; }
        public string ClientresideinruralID { get; set; }
        public string Nameofmother { get; set; }
        public string Address_Of_Mother { get; set; }
        public string Telephone_Of_Mother { get; set; }
        public string Nameoffather { get; set; }
        public string Address_Of_Father { get; set; }
        public string Telephone_Of_Father { get; set; }
        public string Nameofguardian { get; set; }
        public string Address_Of_Guardian { get; set; }
        public string Guardian_Telephone { get; set; }
        public string Emergency_Contact1 { get; set; }
        public string Emergency_Contact1_HomePhone { get; set; }
        public string Emergency_Contact1_CellPhone { get; set; }
        public string Emergency_Contact2 { get; set; }
        public string Emergency_Contact2_HomePhone { get; set; }
        public string Emergency_Contact2_CellPhone { get; set; }
        public string SicklecelltypeID { get; set; }
        public string Medication { get; set; }
        public string Medication2 { get; set; }
        public string Medication3 { get; set; }
        public string Medication4 { get; set; }
        public string HydroxyureaheardID { get; set; }
        public string HydroxyureatakenID { get; set; }
        public string HydroxyureacurrentlyID { get; set; }
        public string HydroxyureapasttakenID { get; set; }
        public string Hydroxyureadosage { get; set; }
        public string Hydroxyureadosageunknown { get; set; }
        public string Hydroxyureacapsulescolor { get; set; }
        public string Hydroxyureadatelasttaken { get; set; }
        public string Hydroxyureadatepickedup { get; set; }
        public string Pharma1heardID { get; set; }
        public string Pharma1takenID { get; set; }
        public string Pharma1currentlyID { get; set; }
        public string Pharma1pasttakenID { get; set; }
        public string Pharma1dosage { get; set; }
        public string Pharma1dosageunknown { get; set; }
        public string Pharma1capsulescolor { get; set; }
        public string Pharma1datelasttaken { get; set; }
        public string Pharma1datepickedup { get; set; }
        public string Pharma2heardID { get; set; }
        public string Pharma2takenID { get; set; }
        public string Pharma2currentlyID { get; set; }
        public string Pharma2pasttakenID { get; set; }
        public string Pharma2dosage { get; set; }
        public string Pharma2dosageunknown { get; set; }
        public string Pharma2capsulescolor { get; set; }
        public string Pharma2datelasttaken { get; set; }
        public string Pharma2datepickedup { get; set; }
        public string Pharma3heardID { get; set; }
        public string Pharma3takenID { get; set; }
        public string Pharma3currentlyID { get; set; }
        public string Pharma3pasttakenID { get; set; }
        public string Pharma3dosage { get; set; }
        public string Pharma3dosageunknown { get; set; }
        public string Pharma3capsulescolor { get; set; }
        public string Pharma3datelasttaken { get; set; }
        public string Pharma3datepickedup { get; set; }
        public string Comments { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string TimeStamp { get; set; }
        public Nullable<System.DateTime> Datenotescreated { get; set; }
        public string Total_Reimbursement_YTD_2020 { get; set; }
        public string No_of_Paid_Inpatient_Claims { get; set; }
        public string Total_Reimbursement_for_Inpatient_Claims { get; set; }
        public string No_of_Paid_Dental_Claims { get; set; }
        public string Total_Reimbursement_for_Dental_Claims { get; set; }
        public string No_of_Paid_Home_Health_Claims { get; set; }
        public string Total_Reimbursement_for_Home_Health_Claims { get; set; }
        public string No_of_Paid_Professional_Claims { get; set; }
        public string Total_Reimbursement_for_Professional_Claims { get; set; }
        public string No_of_Paid_Long_term_Care_Claims { get; set; }
        public string Total_Reimbursement_for_Long_term_Care_Claims { get; set; }
        public string No_of_Paid_Outpatient_Claims { get; set; }
        public string Total_Reimbursement_for_Outpatient_Claims { get; set; }
        public string No_of_Paid_Pharmacy_Claims { get; set; }
        public string Total_Reimbursement_for_Pharmacy_Claims { get; set; }
        public string No_of_Paid_Compound_Drug_Claims { get; set; }
        public string Total_Reimbursement_for_Compound_Drugs_Claims { get; set; }
        public string No_of_Paid_Crossover_Claims { get; set; }
        public string Total_Reimbursement_for_Crossover_Claims { get; set; }
        public string Adult_Day_Care { get; set; }
        public string Advanced_Practice_Nurse { get; set; }
        public string ADvantage_Home_Delivered_Meals { get; set; }
        public string Ambulatory_Surgical_Services { get; set; }
        public string Architectural_Modification { get; set; }
        public string Audiology_Services { get; set; }
        public string Capitated_Services { get; set; }
        public string Chiropractic_Services { get; set; }
        public string Clinic { get; set; }
        public string Clinics_OSA_Services { get; set; }
        public string Dental { get; set; }
        public string Direct_Support { get; set; }
        public string Employee_Training_Specialist { get; set; }
        public string End_Stage_Renal_Disease { get; set; }
        public string Eye_Care_and_Exams { get; set; }
        public string Eyewear { get; set; }
        public string Group_Home { get; set; }
        public string Home_Health { get; set; }
        public string Homemaker_Services { get; set; }
        public string Hospice { get; set; }
        public string ICF_ID_Services { get; set; }
        public string Inpatient_Services { get; set; }
        public string Insure_Oklahoma_ESI_Out_of_Pocket { get; set; }
        public string Insure_Oklahoma_ESI_Premium { get; set; }
        public string Laboratory_Services { get; set; }
        public string Medical_Supplies_DMEPOS { get; set; }
        public string Medicare_Part_A_and_B_Buy_In_Payments { get; set; }
        public string Medicare_Part_D_Payments { get; set; }
        public string Mid_Level_Practitioner { get; set; }
        public string Nursing_Facility { get; set; }
        public string Nursing_Services { get; set; }
        public string Nutritionist_Services { get; set; }
        public string Other_Practitioner { get; set; }
        public string Outpatient_Hospital { get; set; }
        public string Personal_Care { get; set; }
        public string Physician { get; set; }
        public string Podiatry { get; set; }
        public string Prescribed_Drugs { get; set; }
        public string Psychiatric_Services { get; set; }
        public string Residential_Behavior_Mgmt { get; set; }
        public string Respite_Care { get; set; }
        public string Room_and_Board { get; set; }
        public string School_Based_Services { get; set; }
        public string Self_Directed_Care { get; set; }
        public string Specialized_Foster_Care_or_ID_Services { get; set; }
        public string Targeted_Case_Manager { get; set; }
        public string Therapy_Services { get; set; }
        public string Transportation_Emergency { get; set; }
        public string Transportation_Non_Emergency { get; set; }
        public string X_Ray_Services { get; set; }
        public string Behavioral_Health_Services { get; set; }
        public string Community_Mental_Health { get; set; }
        public string ESI { get; set; }
        public string Uncategorized_Services { get; set; }
        public string Other { get; set; }
        public string Oxbryta { get; set; }
        public string Adakvedo { get; set; }
        public string Dual_or_Non_Dual { get; set; }
        public string Deceased { get; set; }
    }
}
