//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SickeCell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public long ClientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Middle_Initial { get; set; }
        public string UniqueID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Age { get; set; }
        public string AgeGroup { get; set; }
        public string Ageat { get; set; }
        public string Gender { get; set; }
        public string Race { get; set; }
        public string Ethnicity { get; set; }
        public string SSN { get; set; }
        public string Mobile_Number { get; set; }
        public string FullStreetAddress { get; set; }
        public string FullStreetAddress2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string CountyCode { get; set; }
        public string CountyCodeDescription { get; set; }
        public string PhoneNumber { get; set; }
        public string Eligibility { get; set; }
        public string SickleCellDiagnosis { get; set; }
        public string PMPProviderName { get; set; }
        public string CCUCase { get; set; }
        public string Email_Address { get; set; }
        public string ClientresideinruralID { get; set; }
        public string Nameofmother { get; set; }
        public string Address_Of_Mother { get; set; }
        public string Telephone_Of_Mother { get; set; }
        public string Nameoffather { get; set; }
        public string Address_Of_Father { get; set; }
        public string Telephone_Of_Father { get; set; }
        public string Nameofguardian { get; set; }
        public string Address_Of_Guardian { get; set; }
        public string Guardian_Telephone { get; set; }
        public string Emergency_Contact1 { get; set; }
        public string Emergency_Contact1_HomePhone { get; set; }
        public string Emergency_Contact1_CellPhone { get; set; }
        public string Emergency_Contact2 { get; set; }
        public string Emergency_Contact2_HomePhone { get; set; }
        public string Emergency_Contact2_CellPhone { get; set; }
        public string SicklecelltypeID { get; set; }
        public string HydroxyureaheardID { get; set; }
        public string HydroxyureatakenID { get; set; }
        public string HydroxyureacurrentlyID { get; set; }
        public string HydroxyureapasttakenID { get; set; }
        public string Comments { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string TimeStamp { get; set; }
        public Nullable<System.DateTime> Datenotescreated { get; set; }
    }
}
